version: '3'

services:
  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  
  mongo1:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  #db-sql:
  #  image: "mcr.microsoft.com/mssql/server"
  #  environment:
  #      SA_PASSWORD: "Your_password123"
  #      ACCEPT_EULA: "Y"

  flask:
    build: ./flask
    volumes: 
      - ./flask:/usr/src/app
    ports:
      - "5005:5000"
    depends_on:
      - mongo1
      - rabbit1
