version: '3'

services:
  db-sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"

  my-flask:
    build: ./flaskalchemy
    volumes: 
      - ./flaskalchemy:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db-sql